cloud:
  aws:
    credentials:
      accessKeyId: ${ACCESS_KEY_ID}
      secretKey: ${SECRET_KEY}
    region: us-east-1
twilio:
  account_sid: ${ACCOUNT_SID}
  auth_token: ${AUTH_TOKEN}
  from_number: ${FROM_NUMBER}

figensoft:
  url: https://www.postaguvercini.com/api_http
  singleSMS: /sendsms.asp
  username: ${FIGEN SOFT_USERNAME}
  password: ${FIGEN SOFT_PASSWORD}
  timeout: 5s
